### ISSUE TITLE
Datapack Support

### ISSUE THREAD

**Issue by LKD-PIX** [UnhappyCodings/thoriumreactors#7]
### Description

Heya, it would be cool if the ore or world generation features would be defined in the /data folder structure like vanilla ores and features so one could modify or add support for it.
(I'd like to add support in my datapack)
Or as alternative have those features, ore density, spawn height, configurable in a config file.
Either way, it currently does not work with my mod/datapack or just vanilla Datapacks that deepen the world depth

### Links

https://modrinth.com/mod/magmatic-exile

**Comment by UnhappyCodings** [comment]
Hey! Because im using minecrafts ore generation system in either 1.19.2 or 1.20.1, it should be possible to modify those files! I will take a look at it.

**Comment by UnhappyCodings** [comment]
Could you tell in which minecraft version you are experiencing this?

**Comment by LKD-PIX** [comment]
Ah, sorry i didn't specify prior, in 1.19.2 specifically, my datapack is also for that version.
Is there documentation on the layout, i just checked the jar as i do for supporting other mods

**Comment by UnhappyCodings** [comment]
Hey! Sorry for that long pause here, looks like I created the ore generation In-Code and not in jsons, that way you are not able to modify it. I will not change this due to possible incompatibility in future 1.19 releases.
This is also fixed due to forge's removal of In-Code ore generation for 1.20 and above.
